services:
  remixed-dev:
    container_name: remixed-dev
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: always
    command: pnpm dev
    volumes:
      - .:/project
    ports:
      - "5173:5173"
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
    driver: bridge
