version: "3.8"
services:
  frontend-prod:
    container_name: frontend-prod
    build:
      context: .
      target: base
      dockerfile: Dockerfile.prod
    restart: always
    command: npm run start
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
    driver: bridge