version: "3.8"
services:
  frontend-dev:
    container_name: frontend-dev
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
    restart: always
    command: npm run dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3001:3000"
      - "9229:9229"
      - "9230:9230"
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
    driver: bridge