services:
  remixed-dev:
    container_name: remixed-dev
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: always
    command: pnpm dev
    volumes:
      - .:/project # Hot reload friendly ;
      # use ./app:/project/app instead if you don't want any node_modules directory in host.
      # It will kill hot reload if you do so.
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
    driver: bridge
