version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      target: dev
    restart: always
    command: npm run start
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - HOST={$(ip route show | awk '/default/ {print $9}')}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
    driver: bridge