services:
  remixed-prod:
    container_name: remixed-prod
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    restart: always
    command: pnpm start
    ports:
      - "3003:3000"
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
    driver: bridge
